
class xpath_store:
    iframe = "//iframe[@id='webklipper-publisher-widget-container-notification-frame']"
    close_iframe_banner = "//a[@id='webklipper-publisher-widget-container-notification-close-div']"
    close_modal_login = "//span[@data-cy='closeModal']"
    logo = "//img[@src='//imgak.mmtcdn.com/pwa_v3/pwa_hotel_assets/header/mmtLogoWhite.png']"
    account_button = "//li[@data-cy='account']"
    username = "//input[@id='username']"
    continue_btn = "//button[@class='capText font16']"
    password = "//input[@id='password']"
    login_btn = "//button[@data-cy='login']"
    server_error = "//span[@data-cy='serverError']"
    close_login = "//span[@data-cy='CommonModal_3']"
    otp = "//input[@id='otp']"
    oneway = "//li[@data-cy='oneWayTrip']"
    fromcity = "//input[@class='fsw_inputField lineHeight36 latoBlack font30' and  @id='fromCity']"
    tocity = "//input[@id='toCity' and @class='fsw_inputField lineHeight36 latoBlack font30']"
    airport_selector = "//div[@class='calc60'][1]"
    search = "//a[@class='primaryBtn font24 latoBold widgetSearchBtn ']"
    overlay_cross = "//span[@class='bgProperties icon20 overlayCrossIcon']"
    airline_name = "//p[contains(@class, 'airlineName')]"
    airline_code = "//p[contains(@class, 'fliCode')]"
    prefer_selector = "//*[contains(text(),'You May Prefer')]"
    view_price = "(//span[@class='appendRight8'])[1]"
    book_now = "(//button[@class='button corp-btn latoBlack buttonPrimary fontSize13  '])[1]"
    fare_summary = "//p[@class='fontSize18 blackFont']"
    flight_name = "(//p[@class='makeFlex hrtlCenter gap-x-10']/span)[1]"
    round = "//li[@data-cy='roundTrip']"
    flight_traveller = "//div[@data-cy='flightTraveller']"
    adults = "//li[@data-cy='adults-2']"
    children = "//li[@data-cy='children-2']"
    travel_class = "//li[@data-cy='travelClass-1']"
    traveller_apply = "//button[@data-cy='travellerApplyBtn']"
    more_airlines = "//p[contains(text(), 'Alliances & Airlines')]/following-sibling::div/child::div[@class='filtersOuter']/child::div/child::p/child::span"
    british_airways = "//div[@class='checkboxContent']/p[contains(text(), 'British Airways ')]"
    view_flight_details = "(//span[@class='linkText ctaLink viewFltDtlsCta'])[1]"
    checkin = "(//span[@class='baggageInfoText darkText'])[14]"
    cabin = "(//span[@class='baggageInfoText darkText'])[15]"
    view_round_fare = "(//button[@class='ViewFareBtn  text-uppercase  clusterBtn'])[1]"
    round_continue = "//button[contains(text(),'Continue')]"
   